#!/usr/bin/env python3
"""
Build data.js from data/*.json.

    python3 os/scripts/build.py

jesus-os machine layer. Markdown is the source of truth for prose; data/*.json
for anything scored. Computes monthly task scores, rollover ages and
month-over-month deltas of the five core metrics, then emits data.js for
dashboard.html. Standard library only. Inherited from segnals-os / life-os;
rebased for Hey Jesus 2026-08-12.
"""
import json, os, sys, datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from docs import load_docs

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = os.path.join(ROOT, "data")

CORE_METRICS = ["conversations", "visitors", "knowledgeFiles", "voices", "languages"]


def load(name):
    with open(os.path.join(D, name), encoding="utf-8") as f:
        return json.load(f)


def month_key(s):  # "2026-08" -> 24320
    y, m = s.split("-")
    return int(y) * 12 + int(m)


def next_month(s):
    y, m = map(int, s.split("-"))
    return f"{y + (m == 12)}-{(m % 12) + 1:02d}"


def build():
    static = load("static.json")
    tasksdoc = load("tasks.json")
    periods = load("periods.json")
    wins = load("wins.json")["wins"]
    plans = load("plans.json")
    sync = load("sync.json")

    tasks = tasksdoc["tasks"]
    today = datetime.date.today()
    current = f"{today.year}-{today.month:02d}"
    curk = month_key(current)

    # ── ROLLOVER ── an open task whose month has passed rolls forward and ages.
    # Age 3+ is flagged: do it or kill it. Silent perpetual carry is the failure
    # mode this exists to prevent.
    for t in tasks:
        if t["status"] == "open" and month_key(t["month"]) < curk:
            age, m = 0, t["month"]
            while month_key(m) < curk:
                m = next_month(m)
                age += 1
            t["rolledFrom"], t["month"], t["age"] = t["month"], current, age
        t["stale"] = t["status"] == "open" and t.get("age", 0) >= 3

    # ── SCORING ── effort = completed weights; outcome = points for real change.
    months = {}
    for t in tasks:
        m = months.setdefault(t["month"], {"effort": 0, "done": 0, "open": 0,
                                           "openWeight": 0, "byCat": {}, "stale": 0})
        if t["status"] == "done":
            m["effort"] += t["weight"]
            m["done"] += 1
            m["byCat"][t["cat"]] = m["byCat"].get(t["cat"], 0) + t["weight"]
        else:
            m["open"] += 1
            m["openWeight"] += t["weight"]
            if t["stale"]:
                m["stale"] += 1

    for mid, outs in periods.get("outcomes", {}).items():
        months.setdefault(mid, {"effort": 0, "done": 0, "open": 0,
                                "openWeight": 0, "byCat": {}, "stale": 0})
        months[mid]["outcome"] = sum(o.get("points", 0) for o in outs)
        months[mid]["outcomes"] = outs

    rows, prev = [], None
    for mo in periods["months"]:
        sc = months.get(mo["id"], {"effort": 0, "done": 0, "open": 0,
                                   "openWeight": 0, "byCat": {}, "stale": 0})
        row = {**mo,
               "effort": sc["effort"], "outcome": sc.get("outcome", 0),
               "score": sc["effort"] + sc.get("outcome", 0),
               "done": sc["done"], "open": sc["open"], "openWeight": sc["openWeight"],
               "stale": sc["stale"], "byCat": sc["byCat"],
               "outcomes": sc.get("outcomes", [])}
        if prev:
            row["delta"] = {
                k: (mo.get(k) - prev.get(k)) if None not in (mo.get(k), prev.get(k)) else None
                for k in CORE_METRICS}
            row["delta"]["score"] = row["score"] - prev["_score"]
        prev = {**mo, "_score": row["score"]}
        rows.append(row)

    data = {
        **static,
        "generated": today.isoformat(),
        "coreMetrics": CORE_METRICS,
        "targets": periods.get("targets", {}),
        "periods": rows,
        "currentMonth": current,
        "weights": tasksdoc["weights"],
        "cats": tasksdoc.get("cats", []),
        "taskList": tasks,
        "wins": wins,
        "plans": {"shortTerm": plans.get("shortTerm", []), "longTerm": plans.get("longTerm", [])},
        "sync": {k: sync[k] for k in ("repo", "lastSyncedCommit", "lastSyncedVersion",
                                      "lastSyncedDate") if k in sync},
        "docs": load_docs(ROOT),
    }

    out = os.path.join(ROOT, "data.js")
    with open(out, "w", encoding="utf-8") as f:
        f.write("// GENERATED by os/scripts/build.py — do not edit by hand.\n")
        f.write("// Edit data/*.json (scored) or the markdown (prose), then rebuild:\n")
        f.write("//     python3 os/scripts/build.py\n")
        f.write(f"// Built: {today.isoformat()}\n")
        f.write("window.NL_DATA = ")
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write(";\n")

    print("✓ data.js written")
    print(f"  months {len(rows)} · tasks {len(tasks)} "
          f"({sum(1 for t in tasks if t['status'] == 'done')} done) · "
          f"score {sum(r['score'] for r in rows)} · wins {len(wins)} · docs {len(data['docs'])}")
    stale = [t for t in tasks if t.get("stale")]
    if stale:
        print(f"  ⚠ {len(stale)} task(s) rolled 3+ times — do them or kill them:")
        for t in stale:
            print(f"      [{t['age']}×] {t['text']}")
    return 0


if __name__ == "__main__":
    sys.exit(build())
